const items = [
    "cat",
    "song",
    "spoon",
    "laptop",
    "t-shirt",
    "book",
    "shoes",
    "coffee mug",
    "keyboard",
    "phone",
    "chair",
    "hat",
    "sunglasses",
    "umbrella",
    "watch",
    "sheep",
    "backpack",
    "pen",
    "headphones",
    "guitar",
    "socks",
    "wallet",
    "bicycle",
    "lamp",
    "couch",
    "pizza",
    "sneakers",
    "camera",
    "toothbrush",
    "scissors",
    "notebook",
    "water bottle",
    "earphones",
    "bracelet",
    "remote control",
    "pillow",
    "calculator",
    "blanket",
    "mouse",
    "screwdriver",
    "car",
    "keychain",
    "sweater",
    "painting",
    "mirror",
    "clock",
    "flowerpot",
    "television",
    "toaster",
    "kettle",
    "glasses",
    "hand",
    "shard",
    "eyeball"
  ];

const verbs = [
    "hides",
    "eats",
    "drinks",
    "writes",
    "reads",
    "buys",
    "cleans",
    "paints",
    "repairs",
    "moves",
    "watches",
    "opens",
    "closes",
    "drives",
    "kicks",
    "throws",
    "catches",
    "plays",
    "cooks",
    "cuts",
    "hits",
    "washes",
    "wears",
    "carries",
    "builds",
    "fixes",
    "lifts",
    "pushes",
    "pulls",
    "turns",
    "chooses",
    "sends",
    "receives",
    "cancels",
    "holds",
    "breaks",
    "borrows",
    "lends",
    "kicks",
    "hugs",
    "teaches",
    "learns",
    "sells",
    "counts",
    "calculates",
    "picks",
    "drops",
    "packs",
    "measures",
    "squeezes",
  ];
  const subjects = [
    "girls",
    "boys",
    "cats",
    "souls",
    "illness",
    "people",
    "a person",
    "a flower",
    "a mouse",
    "an elephant",
    "a cat",
    "a dog",
    "a tree",
    "a car",
    "a bicycle",
    "a book",
    "a phone",
    "a computer",
    "a mountain",
    "the sun",
    "the moon",
    "a star",
    "a bird",
    "a fish",
    "a turtle",
    "a spider",
    "a snake",
    "a butterfly",
    "a cloud",
    "a river",
    "the ocean",
    "a city",
    "a country",
    "a planet",
    "a spaceship",
    "a rocket",
    "a superhero",
    "a scientist",
    "an artist",
    "a teacher",
    "a chef",
    "a firefighter",
    "a police officer",
    "a doctor",
    "a nurse",
    "an astronaut",
    "a robot",
    "a dinosaur",
    "a wizard",
    "a vampire",
    "a ghost",
    "a dragon",
    "a unicorn",
];
const savedConceptsDiv = document.getElementById('savedConcepts');

// Rest of your code...
document.getElementById("saveButton").addEventListener("click", saveConcept);

document.getElementById("generateButton").addEventListener("click", generateConcept);
        function saveConcept() {
          const outputParagraph = document.getElementById('output');
          const currentConcept = outputParagraph.textContent;
          const savedConceptDiv = document.createElement('div');
          savedConceptDiv.textContent = currentConcept;
            
            // Append the saved concept div to the savedConceptsDiv
            savedConceptsDiv.appendChild(savedConceptDiv);

        }
        function generateConcept() {
            const randomItem = items[Math.floor(Math.random() * items.length)];
            const randomVerb = verbs[Math.floor(Math.random() * verbs.length)];
            const randomSubject = subjects[Math.floor(Math.random() * subjects.length)];

            const concept = `${randomItem} that ${randomVerb} ${randomSubject}`;
            document.getElementById("output").textContent = concept;
            
        }
